server:
  port: "5002"

spring:
  redis:
    port: "6379"
    host: "redis-cluster-ip-service"
  cloud:
    stream:
      bindings:
        inboundPostsChanges:
          destination: postsChangeTopic
          content-type: application/json
          group: finderGroup
      kafka:
        binder:
          brokers: kafka-cluster-ip-service

my:
  services:
    posts: posts-cluster-ip-service

management:
  endpoints:
    web:
      exposure:
        include: "info, health"

logging:
  level:
    org.springframework: WARN
    org.mike: DEBUG
