server:
  port: "5002"

spring:
  redis:
    port: "6379"
    host: "redis-cluster-ip-service"
  rabbitmq:
    host: rabbit-cluster-ip-service
    port: 5672
  sleuth:
    propagation-keys: x-request-id, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags, x-ot-span-context

security:
  oauth2:
    resource:
      user-info-uri: http://auth-cluster-ip-service:5005/user/

my:
  services:
    posts: posts-cluster-ip-service
  event:
    queue: postsChangeEvent

management:
  endpoints:
    web:
      exposure:
        include: "info, health"

logging:
  level:
    org.springframework: WARN
    org.mike: DEBUG
