server:
  port: "5002"

spring:
  redis:
    port: "6379"
    host: "redis.rk6ewl.ng.0001.euc1.cache.amazonaws.com"

my:
  services:
    posts: 18.159.45.126

management:
  endpoints:
    web:
      exposure:
        include: "*"
