server:
  port: "5002"

spring:
  redis:
    port: "6379"
    host: "localhost"
  rabbitmq:
    host: localhost
    port: 5672
  sleuth:
    propagation-keys: x-request-id, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags, x-ot-span-context

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5005/user/
    client:
      grant-type: client_credentials

my:
  services:
    posts: localhost
  event:
    queue: postsChangeEvent

management:
  endpoints:
    web:
      exposure:
        include: "*"
