server:
  port: "5002"

spring:
  redis:
    port: "6379"
    host: "localhost"
#  cloud:
#    stream:
#      bindings:
#        inboundPostsChanges:
#          destination: "postsChangeTopic"
#          content-type: "application/json"
#          group: "finderGroup"
#      kafka:
#        binder:
#          brokers: "localhost"
  rabbitmq:
    host: localhost
    port: 5672

my:
  services:
    posts: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
