server:
  port: "5002"

spring:
  redis:
    port: "6379"
    host: "redis-cluster-ip-service"

my:
  services:
    posts: posts-cluster-ip-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web: WARN
    org.springframework.data: DEBUG
    javax.persistence: DEBUG
    org.mike: DEBUG
